# CI de Nível 01 - Disparo Manual através de clique

# nome da pipeline
name: "Execução Manual"

# gatilhos / triggers - regras de disparo
# gatilho manual = workflow_dispatch
on:
    workflow_dispatch:

#tarefas dentro da pipeline = jobs
jobs:
    #nome do job para validacao padroes de codigo estático
    lint:
        # maquina onde o job vai rodar
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: read

        # passos do job
        steps:
          - name: Checkout do código
          # clone do projeto
            uses: actions/checkout@v5
                     
          - name: Executar Super-Linter
            uses: github/super-linter/slim@v5
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              VALIDATE_ALL_CODEBASE: false
              DEFAULT_WORKFLOW: master









              
              

    #nome do job para testes end-to-end
    e2e:
      needs: lint
      runs-on: ubuntu-latest
      steps:
      - name: Checkout do código
        uses: actions/checkout@v5

      # instalação do node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.x    
                                            
      # instalação do Yarn
      - name: Instalando Yarn
        run: npm install -g yarn
            
      # instalação das dependências
      - name: Instalando dependências
        run: yarn
            
      # instalação dos Browsers do Playwright
      - name: Instalando Browsers do Playwright
        run: yarn playwright install
            
      # executar os testes e2e
      - name: Executando testes e2e
        run: yarn run e2e