# CI de Nível 01 - Disparo Manual através de clique

# nome da pipeline
name: "Execução Manual"

# gatilhos / triggers - regras de disparo
# gatilho manual = workflow_dispatch
on:
    workflow_dispatch:

#tarefas dentro da pipeline = jobs
jobs:
    #nome do job para validacao padroes de codigo estático
    lint:
        # maquina onde o job vai rodar
        runs-on: ubuntu-latest
        #runs-on: self-hosted
        permissions:
            contents: read
            packages: read

        # passos do job
        steps:
          - name: Checkout do código
          # clone do projeto
            uses: actions/checkout@v5
                     
          - name: Executar Super-Linter
            uses: github/super-linter/slim@v5
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              VALIDATE_ALL_CODEBASE: true
              DEFAULT_WORKFLOW: master  
              # Regex para incluir apenas o arquivo específico, ignorando caminhos absolutos
              FILTER_REGEX_INCLUDE: '.*src/components/choose-ride\.component\.js$'
              #FILTER_REGEX_INCLUDE: .*src/.*
             
    #nome do job para testes end-to-end
    e2e:
      needs: lint
      runs-on: self-hosted
      steps:
      - name: Checkout do código
        uses: actions/checkout@v5

      # instalação do node
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24.x
          cache: 'yarn'    
                                            
      # instalação do Yarn
      - name: Habilitar Corepack e Yarn
        run: |
          corepack enable
          corepack prepare yarn@stable --activate
        #run: npm install -g yarn
            
      # instalação das dependências
      - name: Instalando dependências do projeto
        run: yarn install --frozen-lockfile
            
      # instalação dos Browsers do Playwright
      - name: Instalando Browsers do Playwright
        #run: yarn playwright install
        run: npx playwright install-deps chromium

      - name: Instalar browser Chromium
      run: npx playwright install chromium
            
      # executar os testes e2e
      - name: Executando testes e2e
        run: yarn run e2e